services:
  - type: web
    plan: free
    name: Digital-test
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 bot.py
    repo: https://github.com/DigitalBotz/Digital-test.git
    branch: main
    autoDeploy: True
    
